In [5]:
import pandas as pd
import glob

import numpy as np
results = pd.concat([pd.read_csv(f) for f in glob.glob('data/result*')], ignore_index=True)
results = results.groupby(["experiment", "hierarchy"]).agg(
    in_top_one=('in_top_one', "sum"), 
    in_top_three=('in_top_three', "sum"), 
    in_top_ten=('in_top_ten', "sum"), 
    n = ('in_top_ten', "count")
).reset_index()

results.in_top_one = results.in_top_one / results.n
results.in_top_three = results.in_top_three / results.n
results.in_top_ten = results.in_top_ten / results.n

results.sort_values(["hierarchy", "experiment"])

              experiment hierarchy  in_top_one  in_top_three  in_top_ten    n
0    sentence_similarity       F01    0.187500       0.46875    0.468750   32
27  zero_shot_hypothesis       F01    0.000000       0.06250    0.125000   32
54      zero_shot_simple       F01    0.000000       0.00000    0.000000   32
1    sentence_similarity       F02    0.065934       0.10989    0.142857   91
28  zero_shot_hypothesis       F02    0.000000       0.00000    0.054945   91
..                   ...       ...         ...           ...         ...  ...
52  zero_shot_hypothesis  baseterm    0.108000       0.14800    0.226000  500
79      zero_shot_simple  baseterm    0.100000       0.18800    0.340000  500
26   sentence_similarity    facets    0.000000       0.00000    0.000000  500
53  zero_shot_hypothesis    facets    0.000000       0.00000    0.000000  500
80      zero_shot_simple    facets    0.000000       0.00000    0.000000  500

[81 rows x 6 columns]